### ISSUE TITLE
Error while running `make dev_database`

### ISSUE THREAD

**Issue by Faisal-Manzer** [carpentries/amy#1586]
I am trying to run `make dev_database` in a virtualenv. This was the traceback it gives on error. I also tried to rerun the script but that failed again.
```
python3 manage.py fake_database
Generating 4 auth groups...
Generating 0 fake airports...
Generating 6 fake roles...
Generating 13 fake tags...
Generating 10 fake badges...
Generating 30 fake instructors...
Generating 10 fake trainers...
Generating 10 fake admins...
Generating 10 fake organizations...
Generating 10 fake memberships...
Generating 5 fake current events...
Generating 5 fake unpublished events...
Generating 5 fake self organized events...
Generating 10 fake train-the-trainer events...
Generating 120 fake tasks...
Generating 30 fake trainees (and their training progresses and training requests)...
Generating 20 fake unmatched training requests...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Delete the database, and rerun this script.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
```
Traceback (most recent call last):
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: workshops_person.twitter

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/user/Desktop/opensource/amy/amy/workshops/management/commands/fake_database.py", line 817, in handle
    raise e
  File "/Users/user/Desktop/opensource/amy/amy/workshops/management/commands/fake_database.py", line 808, in handle
    self.fake_unmatched_training_requests()
  File "/Users/user/Desktop/opensource/amy/amy/workshops/management/commands/fake_database.py", line 494, in fake_unmatched_training_requests
    self.fake_training_request(None)
  File "/Users/user/Desktop/opensource/amy/amy/workshops/management/commands/fake_database.py", line 244, in fake_training_request
    person = self.fake_person(is_instructor=False)
  File "/Users/user/Desktop/opensource/amy/amy/workshops/management/commands/fake_database.py", line 346, in fake_person
    country=choice(Countries)[0],
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/user/Desktop/opensource/amy/amy/workshops/models.py", line 746, in save
    super().save(*args, **kwargs)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql
    cursor.execute(sql, params)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/user/Desktop/opensource/amy/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: workshops_person.twitter
make: *** [dev_database] Error 1
```

**Comment by pbanaszkiewicz** [comment]
Hello @Faisal-Manzer. Thanks for reaching out to us about this error.

I can confirm that `make dev_database` works fine. It uses random data, and sometimes it happens that the script wants to use that random data in a unique-restricted field (`Person.twitter` in your case) more than once. This triggers an error that you posted: `django.db.utils.IntegrityError: UNIQUE constraint failed`.

Remove the database file `db.sqlite3` and rerun the script. It will work (eventually).
